name: r1s(H3) Lean版openwrt

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/r1s_lean_h3.yml'

jobs:

  build:

    runs-on: ubuntu-latest
    if: github.repository == 'fogeater/nanopi-openwrt'

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: . 1_initialization_environment.sh

      - name: Clone Source
        run: . 2_clone_source.sh master-v19.07.1 h3

      - name: Mods
        run: |
          cd friendlywrt-h3
          sed -i 's/CONFIG_TARGET_MULTI_PROFILE/CONFIG_TARGET_sunxi_cortexa7_Default/' configs/config_h3
          sed -i '/CONFIG_TARGET_DEVICE/d' configs/config_h3
          . ../remove_unused_config.sh
          cat ../app_config.seed >> configs/config_h3
          cd friendlywrt
          git remote add upstream https://github.com/coolsnowwolf/openwrt && git fetch upstream
          git checkout upstream/lede-17.01 -b tmp
          #git checkout 33f7cb735300bd9a099995236ed768c8925fec75 -- target/linux/sunxi/image/
          git rm README.md
          git commit -m 'reset'
          git checkout master-v19.07.1
          git rebase adc1a9a3676b8d7be1b48b5aed185a94d8e42728^ --onto tmp -X theirs
          rm -f target/linux/allwinner-h5/patches-4.14/0001-net-thunderx-workaround-BGX-TX-Underflow-issue.patch target/linux/generic/hack-4.14/999-net-patch-linux-kernel-to-support-shortcut-fe.patch
          git checkout upstream/lede-17.01 -- feeds.conf.default && sed -i -E 's/#(src-git.+)(helloworld.+)/\1\2/' feeds.conf.default
          curl 'https://git.openwrt.org/?p=openwrt/openwrt.git;a=patch;h=22378beb581b113def1dc392ef75306a2168a163' | git apply --reject - || true
          . ../../3_prepare_packages.sh
          git apply ../../enable_autocore.diff
          . ../../5_mods.sh

      - name: Build FriendlyWrt
        run: . 4_build_image.sh friendlywrt-h3 nanopi_r1s_h3.mk

      - name: Assemble Artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          find friendlywrt-h3/out/ -name "FriendlyWrt_*img.zip*" | xargs -i mv -f {} ./artifact/
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: FriendlyWrt_NanoPi-R1S H3 lean v19.07
          path: ./artifact/
